- name: Install IIS Web Server and set default page
  hosts: windows
  vars:
    site_template: |
        <html><body style='color: {{ webcolor }};'>Hello from {{ hostname }} !</body></html>
  tasks:
    - name: Install IIS Feature
      win_feature:
        name: Web-Server
        state: present
        include_management_tools: true

    - name: Set homepage for www.windows.com
      win_shell: |
        $html = "{{ site_template }}"
        Set-Content -Path "C:\inetpub\wwwroot\index.html" -Value $html -Force