- name: Setup DNS Server
  hosts: linux
  become: yes
  vars:
    zone_name: linux.com
    zone_file: db.linux.com
    web_servers:
      - "10.0.10.11"  # lin1
      - "10.0.10.12"  # lin2
    forwarders:
      - 8.8.8.8
      - 1.1.1.1

  tasks:
    - name: Install bind9
      apt:
        name: bind9
        state: present
        update_cache: yes

    - name: Ensure zone directory exists
      file:
        path: /etc/bind/zones
        state: directory

    - name: Create zone config file
      copy:
        dest: /etc/bind/named.conf.local
        content: |
          zone "{{ zone_name }}" {
              type master;
              file "/etc/bind/zones/{{ zone_file }}";
          };

    - name: Generate zone file with A records
      copy:
        dest: /etc/bind/zones/{{ zone_file }}
        content: |
          $TTL 604800
          @   IN  SOA ns.{{ zone_name }}. root.{{ zone_name }}. (
                  2         ; Serial
                  604800     ; Refresh
                  86400      ; Retry
                  2419200    ; Expire
                  604800 )   ; Negative Cache TTL
          ;
          @       IN  NS      ns.{{ zone_name }}.
          ns      IN  A       10.0.10.11
          {{ zone_name }}. IN A 10.0.10.11
          lin1    IN  A       {{ web_servers[0] }}
          lin2    IN  A       {{ web_servers[1] }}

    - name: Enable and restart bind9
      service:
        name: bind9
        state: restarted
        enabled: yes