version: "3.9"
services:
  lin1:
    build:
      context: ./node
    container_name: lin1
    hostname: node1
    networks:
      - ansible_net
    ports:
      - "10122:22"
    tty: true
    stdin_open: true

  lin2:
    build:
      context: ./node
    container_name: lin2
    hostname: node2
    networks:
      - ansible_net
    ports:
      - "10222:22"
    tty: true
    stdin_open: true

  # win:
  #   build:
  #     context: ./node
  #   container_name: win
  #   hostname: win
  #   networks:
  #     - ansible_net
  #   ports:
  #     - "10322:22"
  #   tty: true
  #   stdin_open: true

  ansible:
    build:
      context: ./controller
    container_name: ansible
    hostname: ansible
    networks:
      - ansible_net
    volumes:
      - ../workfolder:/home/user/workfolder
    tty: true
    stdin_open: true
    depends_on:
      - lin1
      - lin2
      # - win

networks:
  ansible_net:
    driver: bridge