- name: Set DNS client configuration
  hosts: windows
  tasks:
    - name: Set DNS servers
      win_dns_client:
        adapter_names: '*'
        dns_servers:
          - 10.0.10.20
          - 10.0.10.11