- name: Configure DNS Server on Windows
  hosts: windows
  vars:
    ip_dns: "10.0.10.20"        # IP DNS server (yang akan direkam di A record)
    hostname: "win"             # Nama host DNS (hostname server)
  tasks:
    - name: Ensure DNS feature is installed
      ansible.windows.win_feature:
        name: DNS
        state: present
        include_management_tools: true

    - name: Ensure DNS service is running
      ansible.windows.win_service:
        name: DNS
        state: started
        start_mode: auto

    - name: Ensure primary DNS zone exists
      ansible.windows.win_dns_zone:
        name: windows.com
        type: primary
        replication: none
        state: present

    - name: Add A record for @
      ansible.windows.win_dns_record:
        name: "@"
        type: A
        value: "{{ ip_dns }}"
        zone: "windows.com"
        state: present

    - name: Add A record for hostname
      ansible.windows.win_dns_record:
        name: "{{ hostname }}"
        type: A
        value: "{{ ip_dns }}"
        zone: "windows.com"
        state: present

    - name: Add A record for www
      ansible.windows.win_dns_record:
        name: "www"
        type: A
        value: "{{ ip_dns }}"
        zone: "windows.com"
        state: present
