- name: Import users from CSV
  hosts: linux
  become: yes
  vars:
    csv_bastion: /home/user/workfolder/users.csv
    csv_file: /tmp/users.csv

  tasks:
    - name: Copy CSV file to remote host
      copy:
        src: "{{ csv_bastion }}"
        dest: "{{ csv_file }}"

    - name: Read user CSV file
      slurp:
        src: "{{ csv_file }}"
      register: csv_content

    - name: Parse CSV content with ';' delimiter
      set_fact:
        users_raw: "{{ csv_content['content'] | b64decode | splitlines()[1:] }}"

    - name: Convert raw CSV lines into structured dict
      set_fact:
        users_parsed: >-
          {{
            users_raw |
            map('split', ';') |
            map('zip', ['uid', 'username', 'password', 'home']) |
            map('community.general.dict') |
            list
          }}

    - name: Generate password hashes
      set_fact:
        users_hashed: "{{ users_hashed | default([]) + [ item | combine({ 'password': (item.password | password_hash('sha512')) }) ] }}"
      loop: "{{ users_parsed }}"
      loop_control:
        label: "{{ item.username }}"
    
    - name: Ensure users are present
      ansible.builtin.user:
        name: "{{ item.username }}"
        uid: "{{ item.uid | int }}"
        password: "{{ item.password }}"
        home: "{{ item.home }}"
        state: present
        update_password: on_create
        create_home: yes
      loop: "{{ users_hashed }}"