- name: Configure DNS Clients
  hosts: linux
  become: yes
  vars:
    dns_servers:
      - "10.0.10.11"
      - "10.0.10.12"

  tasks:
    - name: Backup original resolv.conf
      copy:
        src: /etc/resolv.conf
        dest: /etc/resolv.conf.bak
        remote_src: yes
        force: yes

    - name: Set DNS nameservers
      copy:
        dest: /etc/resolv.conf
        content: |
          # Managed by Ansible
          {% for ip in dns_servers %}
          nameserver {{ ip }}
          {% endfor %}